# Generated by Django 5.0.7 on 2024-07-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_descript_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='descript',
            field=models.TextField(null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Imagem do Produto'),
        ),
    ]
